services:
  mongo:
    image: mongo:7
    container_name: monorepo-mongo
    ports:
      - "27017:27017"
    command: mongod --replSet rs0 --bind_ip 0.0.0.0
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
